server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
      
  datasource:
    url: jdbc:mysql://url:3306/appdb
    password: ZmsdfsdfEE71kuDGOzFu0TKGfe
    username: aderwremin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://33.4.10.176:8761/eureka/
      
      
jwt:
  secret: 'sldkjflskdajflk;sdajf3wq4324bwkjfsdk3$23$@#$@#!#$%$%^%^YFDDSFSADFRE'
  

      
 
